app:
  title: Ecommerce Veiculos
  baseUrl: ${APP_BASE_URL}

organization:
  name: Ecommerce Veiculos

backend:
  # auth:
  #   environment: production
  #   providers:
  #     guest:
  #       enabled: true
  #     github:
  #       production:
  #         clientId: ${GITHUB_CLIENT_ID}
  #         clientSecret: ${GITHUB_CLIENT_SECRET}
  #         signIn:
  #           resolvers:
  #             - resolver: usernameMatchingUserEntityName
  #       dangerouslyAllowSignInWithoutUserInCatalog: true
  #   session:
  #     secret: ${BACKEND_SECRET}
  #   externalAccess:
  #     - type: static
  #       allowed: ['*']
  #       options:
  #         subject: external
  #         token: ${BACKEND_SECRET}
  baseUrl: ${BACKEND_BASE_URL}
  # Auth completamente desabilitado
  cache:
    store: memory
  listen:
    port: ${PORT}
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: false
    allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With']
  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl: 
        rejectUnauthorized: false
        require: true
    # Configurações adicionais para produção
    pool:
      min: 1
      max: 5
      acquireTimeoutMillis: 30000
      createTimeoutMillis: 30000
      destroyTimeoutMillis: 5000
      idleTimeoutMillis: 30000
      reapIntervalMillis: 1000
      createRetryIntervalMillis: 200
    # Forçar migrações
    migrations:
      directory: 'migrations'
      tableName: 'migrations'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
    # Configuração para o repositório do catálogo
    - host: github.com
      token: ${GITHUB_TOKEN}
      apiBaseUrl: https://api.github.com

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
  # Configuração para integração com GitHub
  requestUrl: ${BACKEND_BASE_URL}
  storageUrl: ${BACKEND_BASE_URL}/api/techdocs/static/docs
  # Configuração para repositórios GitHub
  discovery:
    policy: 'all'
  # Configuração para GitHub como fonte
  github:
    apiBaseUrl: https://api.github.com
    token: ${GITHUB_TOKEN}

# auth:
#   providers:
#     guest:
#       enabled: true
#   session:
#     secret: ${BACKEND_SECRET}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User, Domain]
  locations:
    # Catálogo principal do repositório GitHub
    - type: url
      target: https://raw.githubusercontent.com/emingues-xx/catalog/main/catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, Group, User, Domain]
    # Usuário local para autenticação GitHub
    - type: file
      target: /app/users.yaml
      rules:
        - allow: [User, Group]

# Configuração de auth para o frontend
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}

# Configuração de permissões
permission:
  enabled: true
  policy:
    default: allow
