app:
  title: Ecommerce Veiculos
  baseUrl: ${APP_BASE_URL}

organization:
  name: Ecommerce Veiculos

backend:
  auth:
    externalAccess:
      - subject: external
        allowed: ['*']
  baseUrl: ${BACKEND_BASE_URL}
  cache:
    store: memory
  listen:
    port: ${PORT}
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl: 
        rejectUnauthorized: false
    # Configurações adicionais para produção
    pool:
      min: 2
      max: 10

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: url
      target: https://raw.githubusercontent.com/emingues-xx/catalog/main/catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, Group, User, Domain, Template]

permission:
  enabled: true
