app:
  title: Ecommerce Veiculos
  baseUrl: ${APP_BASE_URL}

organization:
  name: Ecommerce Veiculos

backend:
  auth:
    environment: production
    providers:
      github:
        production:
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          signIn:
            resolvers:
              - resolver: usernameMatchingUserEntityName
        dangerouslyAllowSignInWithoutUserInCatalog: true
    session:
      secret: ${BACKEND_SECRET}
  baseUrl: ${BACKEND_BASE_URL}
  cache:
    store: memory
  listen:
    port: ${PORT}
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: false
    allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With']
  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl: 
        rejectUnauthorized: false
        require: true
    pool:
      min: 1
      max: 5
      acquireTimeoutMillis: 30000
      createTimeoutMillis: 30000
      destroyTimeoutMillis: 5000
      idleTimeoutMillis: 30000
      reapIntervalMillis: 1000
      createRetryIntervalMillis: 200
    migrations:
      directory: 'migrations'
      tableName: 'migrations'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
    - host: github.com
      token: ${GITHUB_TOKEN}
      apiBaseUrl: https://api.github.com

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
  requestUrl: ${BACKEND_BASE_URL}
  storageUrl: ${BACKEND_BASE_URL}/api/techdocs/static/docs
  discovery:
    policy: 'all'
  github:
    apiBaseUrl: https://api.github.com
    token: ${GITHUB_TOKEN}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User, Domain]
  locations:
    - type: url
      target: https://raw.githubusercontent.com/emingues-xx/catalog/main/catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, Group, User, Domain]
    - type: file
      target: users.yaml
      rules:
        - allow: [User, Group]

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}

permission:
  enabled: true
  policy:
    default: allow
