[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --immutable", "yarn add -D ts-node"]

[phases.build]
cmds = ["yarn tsc"]

[variables]
NODE_VERSION = "20"
NODE_ENV = "production"