[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["yarn tsc", "yarn workspace app build"]

[variables]
NODE_VERSION = "20.18.0"
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20.18.0"