[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["yarn tsc", "cd packages/backend && yarn build"]

[variables]
NODE_VERSION = "20"
NODE_ENV = "production"