[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["yarn workspace backend build", "yarn workspace app build"]

[variables]
NODE_VERSION = "20"
NODE_ENV = "production"